version: '3.1'

services:
  web:
    build:
      context: .
      # args:
      #   - NODE_ENV=development
    # command: /bin/sh -c "npx webpack --watch & npx nodemon --ignore node_modules --inspect=0.0.0.0:8229 dist/server.webpacked.js"
    ports:
      - "3000:3000"
      - "8229:8229"
    volumes:
      - .:/app
    # environment:
    #   - NODE_ENV=development
